//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccademyLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Gen
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public int GenId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
